#!/bin/bash
# ----------------------------------------------------------------------------
# Copyright (c) 2016 by Burkhardt Renz. All rights reserved.
# Bash script
#
# ----------------------------------------------------------------------------
lein eastwood "{:exclude-linters [:constant-test]}"
