#!/bin/bash
# ----------------------------------------------------------------------------
# Copyright (c) 2016 by Burkhardt Renz. All rights reserved.
# Bash script
#
# ----------------------------------------------------------------------------
lein marg -m src/lwb/prop.clj src/lwb/prop/sat.clj
