#!/bin/bash
# ----------------------------------------------------------------------------
# Copyright (c) 2016 - 2020 by Burkhardt Renz. All rights reserved.
# Bash script
#
# ----------------------------------------------------------------------------
lein eastwood "{:exclude-linters [:constant-test] :continue-on-exception true}"
