#!/bin/bash
# ----------------------------------------------------------------------------
# Copyright (c) 2016 by Burkhardt Renz. All rights reserved.
# Bash script
#
# ----------------------------------------------------------------------------
lein marg -m src/lwb/prop.clj src/lwb/prop/sat.clj\
  src/lwb/prop/cardinality.clj src/lwb/prop/bdd.clj\
  src/lwb/pred.clj src/lwb/vis.clj\
  src/lwb/nd/repl.clj src/lwb/nd/proof.clj\
  src/lwb/nd/rules.clj src/lwb/nd/specs.clj\
	src/lwb/nd/io.clj
